### ISSUE TITLE
The java doc is missing

### ISSUE THREAD

**Issue by sindrehauglum** [documaster/ws-client-n5-java#22]
https://github.com/documaster/ws-client-n5-java/blob/65bcf7e7d6f510750423486996fd907c7c043277/src/main/java/com/documaster/rms/noark/ws/noarkentities/Journalpost.java

So I was trying to determine if a field in Journalpost.java was nullable or not. This lead me to this repo and I can not see any java doc.

If I could know the NotNull fields my implementing code could be simplified. 

Regards
The Norwegian Gaming and Foundation Authority

**Comment by dkumanov** [comment]
Hello Sindre,

You can check which fields can be null from our [noark5 webservices documentation](https://github.com/documaster/noark5-web-services/blob/develop/version1/02%20-%20Object%20types.md). Let me know if that suits your need.

Regards,
Dimitar

**Comment by sindrehauglum** [comment]
Yes indeed it does help.

**Comment by sindrehauglum** [comment]
There is a notation 'c' in the table for the field. I can assume it is to tell it conditional. But in the description of notation the 'cm' is used for conditional. What is then 'c'?

**Comment by dkumanov** [comment]
For which field and in which table have you seen the field denoted with 'c'?

**Comment by sindrehauglum** [comment]
Journalpost
![image](https://user-images.githubusercontent.com/22145490/120350934-b55aae00-c2ff-11eb-892c-10befb488557.png)

**Comment by dkumanov** [comment]
This means that either refMappe or refArkivdel should not be null. In general it is a conditional requirement unlike the other places where we use **x**. It would be similar for other such places where this notation is used.

**Comment by sindrehauglum** [comment]
Closing this ticket 
  @dkumanov has provided an answer
